import { describe, expect, it } from "vitest";
import { parseM3u } from "./parseM3u";

describe("parseM3u", () => {
  it("parses extended M3U channels into normalized channel drafts", () => {
    const input = `#EXTM3U
#EXTINF:-1 tvg-id="bbc.one" tvg-logo="https://logo.test/bbc.png" group-title="News",BBC One
https://stream.test/bbc.m3u8
#EXTINF:-1 tvg-id="sky.sports" group-title="Sports",Sky Sports
https://stream.test/sky.ts`;

    const result = parseM3u(input, {
      providerId: "provider-1",
      nowIso: "2026-05-26T12:00:00.000Z"
    });

    expect(result.channels).toHaveLength(2);
    expect(result.channels[0]).toEqual({
      type: "live",
      id: "provider-1:live:bbc-one",
      providerId: "provider-1",
      name: "BBC One",
      logoUrl: "https://logo.test/bbc.png",
      category: "News",
      stream: {
        providerType: "m3u",
        url: "https://stream.test/bbc.m3u8"
      },
      epgChannelId: "bbc.one",
      lastSeenAt: "2026-05-26T12:00:00.000Z",
      isFavorite: false
    });
    expect(result.channels[1]).toEqual({
      type: "live",
      id: "provider-1:live:sky-sports",
      providerId: "provider-1",
      name: "Sky Sports",
      logoUrl: null,
      category: "Sports",
      stream: {
        providerType: "m3u",
        url: "https://stream.test/sky.ts"
      },
      epgChannelId: "sky.sports",
      lastSeenAt: "2026-05-26T12:00:00.000Z",
      isFavorite: false
    });
    expect(result.diagnostics).toEqual([]);
  });

  it("ignores comments and defaults missing optional metadata", () => {
    const input = `#EXTM3U
# Playlist generated by upstream
#EXTINF:-1 tvg-id="public.access" tvg-logo="https://logo.test/public.png",Public Access
#EXTVLCOPT:http-user-agent=iptv-player
https://stream.test/public.m3u8`;

    const result = parseM3u(input, {
      providerId: "provider-1",
      nowIso: "2026-05-26T12:00:00.000Z"
    });

    expect(result.channels).toEqual([
      {
        type: "live",
        id: "provider-1:live:public-access",
        providerId: "provider-1",
        name: "Public Access",
        logoUrl: "https://logo.test/public.png",
        category: "Uncategorized",
        stream: {
          providerType: "m3u",
          url: "https://stream.test/public.m3u8"
        },
        epgChannelId: "public.access",
        lastSeenAt: "2026-05-26T12:00:00.000Z",
        isFavorite: false
      }
    ]);
    expect(result.diagnostics).toEqual([]);
  });

  it("uses Unnamed Channel when EXTINF has no comma-delimited name", () => {
    const input = `#EXTM3U
#EXTINF:-1 group-title="General"
https://stream.test/unnamed.m3u8`;

    const result = parseM3u(input, {
      providerId: "provider-1",
      nowIso: "2026-05-26T12:00:00.000Z"
    });

    expect(result.channels).toEqual([
      {
        type: "live",
        id: "provider-1:live:unnamed-channel",
        providerId: "provider-1",
        name: "Unnamed Channel",
        logoUrl: null,
        category: "General",
        stream: {
          providerType: "m3u",
          url: "https://stream.test/unnamed.m3u8"
        },
        epgChannelId: null,
        lastSeenAt: "2026-05-26T12:00:00.000Z",
        isFavorite: false
      }
    ]);
    expect(result.diagnostics).toEqual([]);
  });

  it("skips malformed entries and records diagnostics", () => {
    const input = `#EXTM3U
#EXTINF:-1 group-title="News",No URL
#EXTINF:-1,Valid Channel
https://stream.test/valid.m3u8`;

    const result = parseM3u(input, {
      providerId: "provider-1",
      nowIso: "2026-05-26T12:00:00.000Z"
    });

    expect(result.channels).toHaveLength(1);
    expect(result.channels[0].name).toBe("Valid Channel");
    expect(result.diagnostics).toContainEqual({
      line: 2,
      message: "EXTINF entry has no following stream URL"
    });
  });

  it("records diagnostics for trailing pending EXTINF entries", () => {
    const input = `#EXTM3U
#EXTINF:-1 group-title="News",No URL`;

    const result = parseM3u(input, {
      providerId: "provider-1",
      nowIso: "2026-05-26T12:00:00.000Z"
    });

    expect(result.channels).toEqual([]);
    expect(result.diagnostics).toEqual([
      {
        line: 2,
        message: "EXTINF entry has no following stream URL"
      }
    ]);
  });

  it("skips stream URLs without preceding EXTINF metadata and records diagnostics", () => {
    const input = `#EXTM3U
https://stream.test/bare.m3u8
#EXTINF:-1,Valid Channel
https://stream.test/valid.m3u8`;

    const result = parseM3u(input, {
      providerId: "provider-1",
      nowIso: "2026-05-26T12:00:00.000Z"
    });

    expect(result.channels).toEqual([
      {
        type: "live",
        id: "provider-1:live:valid-channel",
        providerId: "provider-1",
        name: "Valid Channel",
        logoUrl: null,
        category: "Uncategorized",
        stream: {
          providerType: "m3u",
          url: "https://stream.test/valid.m3u8"
        },
        epgChannelId: null,
        lastSeenAt: "2026-05-26T12:00:00.000Z",
        isFavorite: false
      }
    ]);
    expect(result.diagnostics).toEqual([
      {
        line: 2,
        message: "Stream URL has no preceding EXTINF metadata"
      }
    ]);
  });
});
